package br.mod.escolar.model.entities;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Contact generated by hbm2java
 */
@Entity
@Table(name = "contatos", catalog = "escolar")
public class Contact implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    private Integer id;
    private String email01;
    private String email02;
    private String email03;
    private String telefone01;
    private String telefone02;
    private String telefone03;
    private String telefone01Ddd;
    private String telefone02Ddd;
    private String telefone03Ddd;
    private String celular01;
    private String celular02;
    private String celular03;
    private String celular01Ddd;
    private String celular02Ddd;
    private String celular03Ddd;
    private String fax01;
    private String fax02;
    private String fax03;
    private String fax01Ddd;
    private String fax02Ddd;
    private String fax03Ddd;

    public Contact() {
    }

    public Contact(String email01, String email02, String email03, String telefone01, String telefone02, String telefone03, String telefone01Ddd, String telefone02Ddd, String telefone03Ddd, String celular01, String celular02, String celular03, String celular01Ddd, String celular02Ddd, String celular03Ddd, String fax01, String fax02, String fax03, String fax01Ddd, String fax02Ddd, String fax03Ddd) {
        this.email01 = email01;
        this.email02 = email02;
        this.email03 = email03;
        this.telefone01 = telefone01;
        this.telefone02 = telefone02;
        this.telefone03 = telefone03;
        this.telefone01Ddd = telefone01Ddd;
        this.telefone02Ddd = telefone02Ddd;
        this.telefone03Ddd = telefone03Ddd;
        this.celular01 = celular01;
        this.celular02 = celular02;
        this.celular03 = celular03;
        this.celular01Ddd = celular01Ddd;
        this.celular02Ddd = celular02Ddd;
        this.celular03Ddd = celular03Ddd;
        this.fax01 = fax01;
        this.fax02 = fax02;
        this.fax03 = fax03;
        this.fax01Ddd = fax01Ddd;
        this.fax02Ddd = fax02Ddd;
        this.fax03Ddd = fax03Ddd;

    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "email_01", length = 63)
    public String getEmail01() {
        return this.email01;
    }

    public void setEmail01(String email01) {
        this.email01 = email01;
    }

    @Column(name = "email_02", length = 63)
    public String getEmail02() {
        return this.email02;
    }

    public void setEmail02(String email02) {
        this.email02 = email02;
    }

    @Column(name = "email_03", length = 63)
    public String getEmail03() {
        return this.email03;
    }

    public void setEmail03(String email03) {
        this.email03 = email03;
    }

    @Column(name = "telefone_01", length = 15)
    public String getTelefone01() {
        return this.telefone01;
    }

    public void setTelefone01(String telefone01) {
        this.telefone01 = telefone01;
    }

    @Column(name = "telefone_02", length = 15)
    public String getTelefone02() {
        return this.telefone02;
    }

    public void setTelefone02(String telefone02) {
        this.telefone02 = telefone02;
    }

    @Column(name = "telefone_03", length = 15)
    public String getTelefone03() {
        return this.telefone03;
    }

    public void setTelefone03(String telefone03) {
        this.telefone03 = telefone03;
    }

    @Column(name = "telefone_01_ddd", length = 3)
    public String getTelefone01Ddd() {
        return this.telefone01Ddd;
    }

    public void setTelefone01Ddd(String telefone01Ddd) {
        this.telefone01Ddd = telefone01Ddd;
    }

    @Column(name = "telefone_02_ddd", length = 3)
    public String getTelefone02Ddd() {
        return this.telefone02Ddd;
    }

    public void setTelefone02Ddd(String telefone02Ddd) {
        this.telefone02Ddd = telefone02Ddd;
    }

    @Column(name = "telefone_03_ddd", length = 3)
    public String getTelefone03Ddd() {
        return this.telefone03Ddd;
    }

    public void setTelefone03Ddd(String telefone03Ddd) {
        this.telefone03Ddd = telefone03Ddd;
    }

    @Column(name = "celular_01", length = 15)
    public String getCelular01() {
        return this.celular01;
    }

    public void setCelular01(String celular01) {
        this.celular01 = celular01;
    }

    @Column(name = "celular_02", length = 15)
    public String getCelular02() {
        return this.celular02;
    }

    public void setCelular02(String celular02) {
        this.celular02 = celular02;
    }

    @Column(name = "celular_03", length = 15)
    public String getCelular03() {
        return this.celular03;
    }

    public void setCelular03(String celular03) {
        this.celular03 = celular03;
    }

    @Column(name = "celular_01_ddd", length = 3)
    public String getCelular01Ddd() {
        return this.celular01Ddd;
    }

    public void setCelular01Ddd(String celular01Ddd) {
        this.celular01Ddd = celular01Ddd;
    }

    @Column(name = "celular_02_ddd", length = 3)
    public String getCelular02Ddd() {
        return this.celular02Ddd;
    }

    public void setCelular02Ddd(String celular02Ddd) {
        this.celular02Ddd = celular02Ddd;
    }

    @Column(name = "celular_03_ddd", length = 3)
    public String getCelular03Ddd() {
        return this.celular03Ddd;
    }

    public void setCelular03Ddd(String celular03Ddd) {
        this.celular03Ddd = celular03Ddd;
    }

    @Column(name = "fax_01", length = 15)
    public String getFax01() {
        return this.fax01;
    }

    public void setFax01(String fax01) {
        this.fax01 = fax01;
    }

    @Column(name = "fax_02", length = 15)
    public String getFax02() {
        return this.fax02;
    }

    public void setFax02(String fax02) {
        this.fax02 = fax02;
    }

    @Column(name = "fax_03", length = 15)
    public String getFax03() {
        return this.fax03;
    }

    public void setFax03(String fax03) {
        this.fax03 = fax03;
    }

    @Column(name = "fax_01_ddd", length = 3)
    public String getFax01Ddd() {
        return this.fax01Ddd;
    }

    public void setFax01Ddd(String fax01Ddd) {
        this.fax01Ddd = fax01Ddd;
    }

    @Column(name = "fax_02_ddd", length = 3)
    public String getFax02Ddd() {
        return this.fax02Ddd;
    }

    public void setFax02Ddd(String fax02Ddd) {
        this.fax02Ddd = fax02Ddd;
    }

    @Column(name = "fax_03_ddd", length = 3)
    public String getFax03Ddd() {
        return this.fax03Ddd;
    }

    public void setFax03Ddd(String fax03Ddd) {
        this.fax03Ddd = fax03Ddd;
    }

    @Override
    public String toString() {
        return "Contact{" + "id=" + id + "email01=" + email01 + "fax03Ddd=" + fax03Ddd + "}\n";
    }
}
