package br.mod.escolar.model.entities;


import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Documentation generated by hbm2java
 */
@Entity
@Table(name = "documentacoes", catalog = "escolar")
public class Documentation implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    private Integer id;
    private String rg;
    private String rgEmissor;
    private String rgUf;
    private Date rgEmissao;
    private String certidaoCivil;
    private String certidaoCivilLivro;
    private String certidaoCivilFolha;
    private String certidaoCivilCartorio;
    private String certidaoCivilUf;
    private String certidaoCivilTermo;
    private String cpf;

    public Documentation() {
    }

    public Documentation(String rg, String rgEmissor, String rgUf, Date rgEmissao, String certidaoCivil, String certidaoCivilLivro, String certidaoCivilFolha, String certidaoCivilCartorio, String certidaoCivilUf, String certidaoCivilTermo, String cpf) {
        this.rg = rg;
        this.rgEmissor = rgEmissor;
        this.rgUf = rgUf;
        this.rgEmissao = rgEmissao;
        this.certidaoCivil = certidaoCivil;
        this.certidaoCivilLivro = certidaoCivilLivro;
        this.certidaoCivilFolha = certidaoCivilFolha;
        this.certidaoCivilCartorio = certidaoCivilCartorio;
        this.certidaoCivilUf = certidaoCivilUf;
        this.certidaoCivilTermo = certidaoCivilTermo;
        this.cpf = cpf;

    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "rg", length = 31)
    public String getRg() {
        return this.rg;
    }

    public void setRg(String rg) {
        this.rg = rg;
    }

    @Column(name = "rg_emissor", length = 15)
    public String getRgEmissor() {
        return this.rgEmissor;
    }

    public void setRgEmissor(String rgEmissor) {
        this.rgEmissor = rgEmissor;
    }

    @Column(name = "rg_uf", length = 2)
    public String getRgUf() {
        return this.rgUf;
    }

    public void setRgUf(String rgUf) {
        this.rgUf = rgUf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "rg_emissao", length = 10)
    public Date getRgEmissao() {
        return this.rgEmissao;
    }

    public void setRgEmissao(Date rgEmissao) {
        this.rgEmissao = rgEmissao;
    }

    @Column(name = "certidao_civil", length = 63)
    public String getCertidaoCivil() {
        return this.certidaoCivil;
    }

    public void setCertidaoCivil(String certidaoCivil) {
        this.certidaoCivil = certidaoCivil;
    }

    @Column(name = "certidao_civil_livro", length = 63)
    public String getCertidaoCivilLivro() {
        return this.certidaoCivilLivro;
    }

    public void setCertidaoCivilLivro(String certidaoCivilLivro) {
        this.certidaoCivilLivro = certidaoCivilLivro;
    }

    @Column(name = "certidao_civil_folha", length = 63)
    public String getCertidaoCivilFolha() {
        return this.certidaoCivilFolha;
    }

    public void setCertidaoCivilFolha(String certidaoCivilFolha) {
        this.certidaoCivilFolha = certidaoCivilFolha;
    }

    @Column(name = "certidao_civil_cartorio", length = 63)
    public String getCertidaoCivilCartorio() {
        return this.certidaoCivilCartorio;
    }

    public void setCertidaoCivilCartorio(String certidaoCivilCartorio) {
        this.certidaoCivilCartorio = certidaoCivilCartorio;
    }

    @Column(name = "certidao_civil_uf", length = 63)
    public String getCertidaoCivilUf() {
        return this.certidaoCivilUf;
    }

    public void setCertidaoCivilUf(String certidaoCivilUf) {
        this.certidaoCivilUf = certidaoCivilUf;
    }

    @Column(name = "certidao_civil_termo", length = 63)
    public String getCertidaoCivilTermo() {
        return this.certidaoCivilTermo;
    }

    public void setCertidaoCivilTermo(String certidaoCivilTermo) {
        this.certidaoCivilTermo = certidaoCivilTermo;
    }

    @Column(name = "CPF", length = 15)
    public String getCpf() {
        return this.cpf;
    }

    public void setCpf(String cpf) {
        this.cpf = cpf;
    }

    @Override
    public String toString() {
        return "Documentation{" + "id=" + id + " rg=" + rg + " rgEmissor=" + rgEmissor +  " rgUf=" + rgUf + " rgEmissao=" + rgEmissao + " certidaoCivil=" + certidaoCivil + " certidaoCivilLivro=" + certidaoCivilLivro + " certidaoCivilFolha=" + certidaoCivilFolha + " certidaoCivilCartorio=" + certidaoCivilCartorio + " certidaoCivilUf=" + certidaoCivilUf + " certidaoCivilTermo=" + certidaoCivilTermo + " cpf=" + cpf + "}\n";
    }
}

